# Generated by Django 6.0.3 on 2026-03-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0018_appointment_meeting_id_appointment_payment_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smslog',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='meeting_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='sms_sent',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='video_link',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='SMSLog',
        ),
    ]
