# Generated by Django 5.2.12 on 2026-03-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0021_appointment_payment_amount_appointment_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='prescription',
            field=models.TextField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='recommendedtest',
            field=models.TextField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='remark',
            field=models.CharField(default='0', max_length=250),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'admin'), ('2', 'doc')], default='1', max_length=50),
        ),
    ]
